language: node_js
node_js:
  - "8"
 
branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
 
cache:
  directories:
    - node_modules
 
script:
  - npm run build.prod.firebase

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
 
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: dist
#   on:
#     branch: master
