language: node_js
node_js:
  - "8"
 
branches:
  only:
    - master
 
cache:
  directories:
    - node_modules
 
script:
  - npm run build.prod
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "bd1e2fb139372b6c384b3a3eb3a5417555998bc3"
  local_dir: dist
  on:
    branch: master
